apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: site
        image: saminnasr/myfirstsite:latest
        ports:
        - containerPort: 80
